### ISSUE TITLE
installation sandbox problem load_data 

### ISSUE THREAD

**Issue by laghdaf** [sonata-project/sandbox#595]
hi, I just install sonata/sandbox using composer, when I execute "php bin/load_data.php" I got this error
Fail to run: D:\Ampps\php\php.exe -d memory_limit=-1 ./app/console cache:create-
cache-class --env=prod --no-debug

  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
  Unable to parse file "D:\wamp\www\sandbox1\vendor\simplethings\entity-audit
  -bundle\src\SimpleThings\EntityAudit\DependencyInjection/../Resources/confi
  g\current_username.xml".

  [InvalidArgumentException]
  [ERROR 1840] Element '{http://symfony.com/schema/dic/services}argument', at
  tribute 'on-invalid': [facet 'enumeration'] The value 'NULL' is not an elem
  ent of the set {'null', 'ignore', 'exception'}. (in file:///D:/wamp/www/san
  dbox1/ - line 15, column 0)
  [ERROR 1824] Element '{http://symfony.com/schema/dic/services}argument', at
  tribute 'on-invalid': 'NULL' is not a valid value of the atomic type '{http
  ://symfony.com/schema/dic/services}invalid_sequence'. (in file:///D:/wamp/w
  ww/sandbox1/ - line 15, column 0)

**Comment by ahmed-afadil** [comment]
I got the same issue here,

**Comment by greg0ire** [comment]
Does the entity-audit-bundle show up in `composer outdated`?

**Comment by laurentmouren** [comment]
I got the same issue here,

**Comment by greg0ire** [comment]
> Does the entity-audit-bundle show up in composer outdated?

**Comment by laurentmouren** [comment]
no

**Comment by greg0ire** [comment]
Can you try updating it and reporting back?

**Comment by laurentmouren** [comment]
same error when i just try to update it with composer

**Comment by greg0ire** [comment]
Ok so how is this a sonata issue? The file that causes the problem is in a bundle that is not ours.

**Comment by laurentmouren** [comment]
yes sure i will see if it's a problem of version, so you know this version of this bundle isn't good in you "package"

**Comment by laurentmouren** [comment]
ok i change some version. But now on php bin/load_data.php i have error : 
 - Checking Sonata Project's requirements................................KO
Fail to run: C:\Program Files (x86)\EasyPHP-12.1\php\php546x130315102702\php.exe -d memory_limit=-1 ./bin/sonata-check.php
If the error is coming from the sandbox,
please report the issue to https://github.com/sonata-project/sandbox/issues
An error occurs when running a command!

**Comment by dplekhov** [comment]
Yes, the same problem.

**Comment by ekonoval** [comment]
I've gotten the same error but I was performing composer install on just clonned 2.4 branch of sandbox. It seems an error occurs in post-install commands

![89b33ffccc7d486a8f03b01bc8a67da1](https://cloud.githubusercontent.com/assets/3856071/22894444/ad209cb2-f221-11e6-93f1-ae3e0872612c.png)

**Comment by OskarStark** [comment]
This is based on a symfony issue: https://github.com/symfony/symfony/pull/20936

We fixed it by
```diff
         "simplethings/entity-audit-bundle": "^0.9",
         "simplethings/entity-audit-bundle": "^1.0,>=1.0.2",
´´´
since a bugfix in symfony/symfony@>=2.8.16 does not allow empty XML configuration files anymore, see https://github.com/symfony/symfony/pull/20936

**Comment by rnrkrft** [comment]
This error is still in the sandbox. Without xdebug it shows up, with debug enable it is gone, but it gives the notice, that debug is slowing everything down.

**Comment by jordisala1991** [comment]
Fixed in 3.0 branch: https://github.com/sonata-project/sandbox/blob/3.0/composer.json#L68

Closing.
